on:
  push:
    branches:
      - master
  pull_request:

name: Validation

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker build .
  test-usage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          input_path: /
          output_dir: generated
          images_dir: images
          build_html: true
      - uses: actions/upload-artifact@v6
        with:
          name: readme
          path: generated
